# 数据集生成

生成CSV数据表, 定义数据大小为$D = 20, l = 10000 $

### Exampe1

Given $\vec{p}, \vec{q}, Find: $
$$
y = sin(<\bold{p}, \bold{x}>) + cos(<\bold{q}, \bold{x}>)
$$

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 设置随机数种子
np.random.seed(42)

In [3]:
D = 40
# 定义p,q为随机数数组
p = np.random.rand(D)
q = np.random.rand(D)

In [4]:
def func1(p, q, x):
    return np.sin(np.dot(p, x)) + np.cos(np.dot(q, x))

# 生成数据10000个样本, x为0-1的随机数
X = np.random.rand(10000, D)
# 计算y
y = np.array([func1(p, q, x) for x in X])

In [5]:
# 标准化数据
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = scaler.fit_transform(y.reshape(-1, 1)).reshape(-1)

In [6]:
# 保存数据
df = pd.DataFrame(np.hstack([X, y.reshape(-1, 1)]))
df.head()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,1.250107,0.432554,-0.578400,-1.513010,-0.669289,-0.608792,0.804890,0.477470,1.346126,-0.095303,...,-1.177931,1.459452,1.064232,0.473094,1.286367,1.060472,-1.094578,1.355803,0.123127,-1.477687
1,1.058146,1.377502,-0.623408,-1.351336,-0.956631,-0.258621,1.111579,1.248884,-1.707337,0.039080,...,-0.906663,-1.256201,-0.042359,1.684977,-0.900141,0.604080,0.910155,-0.909194,0.774623,0.320275
2,-0.458058,0.463756,0.477930,0.129045,-1.432883,1.143771,-0.613325,-1.081578,-1.590011,0.318591,...,1.370581,1.358135,0.456469,-0.539681,-0.527895,0.790820,1.382501,1.336876,0.952814,0.345420
3,0.487717,-1.435076,-1.169231,1.390551,0.352955,-1.694393,-1.374105,0.567149,-1.713895,-1.181347,...,0.004282,0.238679,-0.031716,-1.034371,0.768722,-0.753833,-1.660227,0.501272,-1.126344,0.486485
4,1.516874,1.577849,1.459923,-0.446858,-1.691805,1.463337,-0.240741,1.615019,1.611169,1.232733,...,1.068974,1.242749,1.429268,0.053149,0.001207,1.041816,0.520902,0.696654,1.007719,0.816467

In [7]:
# 检验数据
print(df.describe())

                 0             1             2             3             4   \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04
mean  -1.058957e-14  5.460521e-15  8.697043e-16  7.168666e-15 -6.041745e-15
std    1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00
min   -1.726049e+00 -1.726020e+00 -1.733265e+00 -1.733476e+00 -1.744936e+00
25%   -8.631114e-01 -8.711409e-01 -8.642318e-01 -8.671187e-01 -8.646919e-01
50%    6.766554e-03  3.674242e-03  3.587360e-03 -5.867705e-03  8.537315e-03
75%    8.675733e-01  8.620147e-01  8.573026e-01  8.548901e-01  8.700628e-01
max    1.721211e+00  1.736938e+00  1.756730e+00  1.743059e+00  1.714203e+00

                 5             6             7             8             9   \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04
mean   7.787548e-16  1.094236e-16 -5.362111e-15  2.254552e-15 -2.078870e-15
std    1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00
min   -1.725211e+00 -1.726090e+00 -1.726156e+00 -1.731284e+00 -1.741964e+00
25%   -8.754365e-01 -8.712742e-01 -8.628098e-01 -8.639390e-01 -8.650254e-01
50%    1.818625e-02 -2.221312e-02  2.392165e-03  6.311703e-03  5.647359e-03
75%    8.703809e-01  8.610282e-01  8.721501e-01  8.707896e-01  8.601154e-01
max    1.709587e+00  1.742201e+00  1.729827e+00  1.736657e+00  1.745341e+00

       ...            31            32            33            34  \
count  ...  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04
mean   ...  3.485212e-15 -7.325696e-16  9.573853e-15  1.319140e-14
std    ...  1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00
min    ... -1.736131e+00 -1.757058e+00 -1.740917e+00 -1.705968e+00
25%    ... -8.741702e-01 -8.606475e-01 -8.687522e-01 -8.694940e-01
50%    ...  1.173552e-02 -3.027393e-03  5.742150e-03 -1.357747e-04
75%    ...  8.713884e-01  8.773311e-01  8.630745e-01  8.679982e-01
max    ...  1.725841e+00  1.702642e+00  1.730427e+00  1.734274e+00

                 35            36            37            38            39  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04
mean   1.492140e-16 -2.798117e-15 -6.195933e-16  1.930189e-15  2.102141e-15
std    1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00
min   -1.740932e+00 -1.728022e+00 -1.744977e+00 -1.730707e+00 -1.737213e+00
25%   -8.595628e-01 -8.678732e-01 -8.591005e-01 -8.598129e-01 -8.642398e-01
50%    7.360427e-03 -1.050963e-02 -4.980942e-03 -1.199164e-02  4.978440e-03
75%    8.601340e-01  8.693445e-01  8.565017e-01  8.652717e-01  8.759804e-01
max    1.732317e+00  1.741575e+00  1.740806e+00  1.726403e+00  1.712044e+00

                 40
count  1.000000e+04
mean  -1.705303e-17
std    1.000050e+00
min   -2.236126e+00
25%   -7.300413e-01
50%   -1.864277e-02
75%    5.936484e-01
max    3.285312e+00

[8 rows x 41 columns]

In [8]:
# 保存数据
df.to_csv('Exampe1_D40.csv', index=False, header=['X'+str(i) for i in range(D)]+['y'])